BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "a-layer"
BBFILE_PATTERN_a-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_a-layer = "10"

LAYERVERSION_a-layer = "1"
LAYERDEPENDS_a-layer = "core raspberrypi"
LAYERSERIES_COMPAT_a-layer = "whinlatter"
